### ISSUE TITLE
Import the Fink web CVS module into git, switch to that

### ISSUE THREAD

**Issue by fingolfin** [fink/web#1]
The code for our website (and manual) is currently still stored in the `web` CVS module (resp. the virtual CVS modules `xml` and `website`, the former of which consists of the `web/xml` subdir, the latter is `web` minus `web/xml`).

Importing the code with its history (with fixed committer names, etc.) to git will be only the first step for that. We also need to adapt the code to work with git.

The primary obstacle I am aware of is that the XML files and surrounding scripts heavily rely on CVS tags like `$Author$` and `$Date$` in order to generate info about who last changed each page, and when.

One way to go about that is to simply remove the use of those tags from the XML files. Then, in the first iteration, just treat them as blank (we loose some nice information on the website, but at least we can switch to git). Better (and the long-term goal) will be to add a preprocess script which, given the XML file, uses git to retrieve the required information about each XML file, and then passes the data on to the XML preprocessor (resp. generates a temporary XML files with the correct data inserted -- but these are implementation details anyway).

Other than that (and some reordering of the file structure), we should be good.

**Comment by akhansen** [comment]
Closing because this was done a while ago.
