### ISSUE TITLE
Add explicit hyperlinks on installation page

### ISSUE THREAD

**Issue by fingolfin** [fink/web#2]
Our primary installation instructions right now are on http://finkproject.org/doc/bundled/install-fast.php resp.  http://finkproject.org/doc/bundled/install-first.php

We mention connect.apple.com several times there, shouldn't we turn this into hyperlinks? More importantly, though, it tells the user to
`Start out by copying the fink-0.35.1.tar.gz file to your home folder [...]`

But as far as I can tell, there are no instructions on how to obtain this. I think we really should provide a hyperlink to it. Or perhaps even add a suitable wget / curl invocation for downloading it. Something like:

  If you have not yet done so, download [fink-0.35.1.tar.gz](http://downloads.sourceforge.net/fink/fink-0.35.1.tar.gz), for example via a webbrowser. Alternatively, you can download it directly in the terminal by entering the following command ... insert suitable curl invocation ...

**Comment by akhansen** [comment]
Closing because these files no longer exist.
